### ISSUE TITLE
Broken Dialogue Flag when learning about Brother's killer

### ISSUE THREAD

**Issue by AzyWng** [JamesB192/Shadowrun-Unlimited-rip#23]
After a few jobs, Gunderson sends you over and explains that the PC's brother's killer showed up, looking for the player in Seattle. Characters with an INT of 4+ or the Security Etiquette can note that it's strange that the killer chose to kill the PC's brother. However, my character had neither of these, but the dialogue option was still available.

I've also seen dialogue issues in other places - when killing a drug dealer, there are several options to take a drug, but only one is available, and when going to help the Organ Grinders operator with thugs harassing her, the player may make a sexist comment, but if the player is female, this option still appears but greyed-out. However, this seemed like one of the bigger issues.

Hopefully development on Shadowrun Unlimited is still going. Love what you've made so far.

**Comment by i30817** [comment]
Greyed out dialog options when you don't have the stats are a engine 'feature' probably because of terrible people that don't have time for games really wanted to be spoiled when replaying for a game where the optional/non-critical-path parts are already kind of weak compared to classics.

**Comment by ChristophFranzen** [comment]
Actually it **is** possible to add and remove menu entries entirely. This works correctly in the PDA's top menu where "Job's done." appears whenever you have completed a run, but not talked about it to your fixer yet. See also issue #39.

Whenever defeating a drug dealer, you can get one portion of one randomly chosen drug type: this is the one associated with the active menu option, the inactive options are for the other drug types. It should be possible to remove the inactive ones entirely, because in the PDA menu (which is also just a "dialogue", I think?) this is done already with the option "Job's done." after completing a run.
